const router = require("express").Router();
const { RegController } = require("../controllers/doctors");
const { UpdateController } = require("../controllers/doctors");
const { DeleteController } = require("../controllers/doctors");
const { GetController } = require("../controllers/doctors");
const authenticateHospital = require("../middleware/authenticateHospital");
router.post("/register",authenticateHospital, RegController);
router.put("/update",authenticateHospital, UpdateController);
router.delete("/delete",authenticateHospital, DeleteController);
router.get("/getAll/:hospitalid",authenticateHospital, GetController);
module.exports = router;
